version: '3.1'

services:
  db:
    container_name: "mysqldb"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ../scripts/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: yofio-test
      MYSQL_USER: 'yofio'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
  
  #   volumes:
  #     - my-db:/var/lib/mysql
  # volumes:
  # my-db: